import mongoose from 'mongoose';
const doctorSchema=new mongoose.Schema({name:{type:String,required:true,unique:true,trim:true},username:{type:String,required:true,unique:true,lowercase:true,trim:true},passwordHash:{type:String,required:true},baseSalary:{type:Number,default:45000},birthYear:{type:Number,default:0},email:{type:String,default:''},role:{type:String,enum:['admin','doctor'],default:'doctor'},telegram:{botToken:{type:String,default:''},chatId:{type:String,default:''},enabled:{type:Boolean,default:false}},resetTokenHash:String,resetTokenExpiresAt:Date},{timestamps:true});
const patientSchema=new mongoose.Schema({gregDate:{type:String,required:true},ethDate:{type:String,required:true},patientName:{type:String,required:true,trim:true},cardNumber:{type:String,default:''},ticketNo:{type:String,default:''},procedure:{type:String,required:true},totalFee:{type:Number,required:true,min:0},doctorPct:{type:Number,default:4,min:0,max:100},myEarning:{type:Number,required:true},doctorId:{type:mongoose.Schema.Types.ObjectId,ref:'Doctor',required:true}},{timestamps:true});
patientSchema.index({doctorId:1,gregDate:1});patientSchema.index({doctorId:1,ethDate:1});patientSchema.index({doctorId:1,patientName:1});
const closureSchema=new mongoose.Schema({doctorId:{type:mongoose.Schema.Types.ObjectId,ref:'Doctor',required:true},ethMonth:{type:String,required:true},ethYear:{type:Number,required:true},earnedAmount:{type:Number,default:0},paidDate:{type:String,required:true},paidEthDate:{type:String,default:''},closedBy:{type:String,default:''}},{timestamps:true});closureSchema.index({doctorId:1,ethMonth:1,ethYear:1},{unique:true});
const auditSchema=new mongoose.Schema({doctorId:mongoose.Schema.Types.ObjectId,doctorName:String,action:String,entity:String,entityId:String,detail:String},{timestamps:true});
const settingSchema=new mongoose.Schema({key:{type:String,unique:true},value:String},{timestamps:true});
const presetSchema=new mongoose.Schema({procedure:{type:String,unique:true},fee:{type:Number,required:true}});
export const Doctor=mongoose.model('Doctor',doctorSchema);export const Patient=mongoose.model('Patient',patientSchema);export const SalaryClosure=mongoose.model('SalaryClosure',closureSchema);export const AuditLog=mongoose.model('AuditLog',auditSchema);export const Setting=mongoose.model('Setting',settingSchema);export const ProcedurePreset=mongoose.model('ProcedurePreset',presetSchema);

const telegramOutboxSchema=new mongoose.Schema({doctorId:{type:mongoose.Schema.Types.ObjectId,ref:'Doctor',required:true},messageText:{type:String,required:true},attempts:{type:Number,default:0},lastError:{type:String,default:''},sentAt:{type:Date,default:null}},{timestamps:true});telegramOutboxSchema.index({sentAt:1,attempts:1,createdAt:1});export const TelegramOutbox=mongoose.model('TelegramOutbox',telegramOutboxSchema);
